steps:

  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: [ '-f','docker-compose.cloudbuild.yaml','up','-d' ]

  - id: "Chown in /var/www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www' ]

  - id: "List all containers"
    name: 'docker'
    args: [ 'ps' ]

  - id: "Run Composer"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec','-t','app','composer','install' ]
